# Generated by Django 6.0.4 on 2026-04-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('notes', models.TextField(blank=True, verbose_name='Notes cliniques')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, verbose_name='Tension artérielle')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de consultation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_realisees', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='Patient')),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('recommandations', models.TextField(blank=True, verbose_name='Recommandations générales')),
                ('duree_traitement', models.CharField(blank=True, max_length=100, verbose_name='Durée du traitement')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation', verbose_name='Consultation')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ordonnance', to='consultations.medicament', verbose_name='Médicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
            },
        ),
    ]
