# Generated by Django 6.0.4 on 2026-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('notes', models.TextField(blank=True, verbose_name='Notes cliniques')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, verbose_name='Tension artérielle')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de consultation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('recommandations', models.TextField(blank=True, verbose_name='Recommandations générales')),
                ('duree_traitement', models.CharField(blank=True, max_length=100, verbose_name='Durée du traitement')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
            },
        ),
    ]
