# Generated by Django 6.0.4 on 2026-05-06 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nouveaux_patients', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique Dashboard',
                'verbose_name_plural': 'Statistiques Dashboard',
                'ordering': ['-date'],
            },
        ),
    ]
